version: "3.9"

services:
  flask-app:
    image: python:3.9-slim
    networks:
      - global
    volumes:
      - ./backend:/app
    working_dir: /app
    command: >
      sh -c "pip install -r requirements.txt && flask run --host=0.0.0.0 --port=5000"
    ports:
      - "5000:5000"
    deploy:
      mode: replicated
      replicas: 4  # Distribui entre os 4 EC2
      restart_policy:
        condition: on-failure

  postgres:
    image: postgres:latest
    networks:
      - global
    environment:
      POSTGRES_DB: cbo_ocupacao
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    deploy:
      replicas: 1  # Banco deve rodar em apenas 1 EC2
      placement:
        constraints:
          - node.role == manager  # Banco fica no Manager Node

  redis:
    image: redis:latest
    networks:
      - global
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager  # Redis no Manager Node

  solr:
    image: solr:latest
    networks:
      - global
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager  # Solr no Manager Node

networks:
  global:
    driver: overlay
